include ../Build/Common/CommonDefs.mak

BIN_DIR = ../Bin

SRC_FILES = \
	./org/openni/Samples/UserTracker/*.java

JAR_NAME = org.openni.Samples.UserTracker
USED_JARS = org.openni
MAIN_CLASS = org.openni.Samples.UserTracker.UserTrackerApplication

LIB_DIRS += ../../Lib
include ../Build/Common/CommonJavaMakefile
