include ../Build/Common/CommonDefs.mak

BIN_DIR = ../Bin

SRC_FILES = \
	./org/openni/Samples/SimpleRead/*.java

JAR_NAME = org.openni.Samples.SimpleRead
USED_JARS = org.openni
MAIN_CLASS = org.openni.Samples.SimpleRead.SimpleRead

LIB_DIRS += ../../Lib
include ../Build/Common/CommonJavaMakefile



