include ../Build/Common/CommonDefs.mak

BIN_DIR = ../Bin

SRC_FILES = \
	./org/openni/Samples/SimpleViewer/*.java

JAR_NAME = org.openni.Samples.SimpleViewer
USED_JARS = org.openni
MAIN_CLASS = org.openni.Samples.SimpleViewer.SimpleViewerApplication

LIB_DIRS += ../../Lib
include ../Build/Common/CommonJavaMakefile
